"""add articles_hashtags associate table

Revision ID: 004e4ad22ecc
Revises: 13e21a0c92b6
Create Date: 2023-03-22 20:08:20.525044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004e4ad22ecc'
down_revision = '13e21a0c92b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_hashtags',
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('hashtag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles_hashtags')
    # ### end Alembic commands ###
