"""add registration column in users

Revision ID: 3fe516899c7f
Revises: 89a0ca612fca
Create Date: 2023-03-22 18:19:28.702644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe516899c7f'
down_revision = '89a0ca612fca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_date')
    # ### end Alembic commands ###
