"""added articles table

Revision ID: 7171cb764ba9
Revises: 1d64f4cbbd4c
Create Date: 2023-03-22 18:50:25.076672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7171cb764ba9'
down_revision = '1d64f4cbbd4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=70), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
