"""rename users authorse

Revision ID: 7286b34b6cd1
Revises: 004e4ad22ecc
Create Date: 2023-03-22 20:54:44.081357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7286b34b6cd1'
down_revision = '004e4ad22ecc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
